adjective1 = input("Enter adjective(description): ")
noun1 = input("Enter noun(place,things,person): ")
adjective2 = input("Enter adjective(description): ")
verb1 = input("Enter verb end with 'ing': ")
adjective3 = input("Enter adjective(description): ")
print(f"today i want to {adjective1} zoo. ")
print(f"in an exhibit, i saw a {noun1}")
print(f"{noun1} was {adjective2} and {verb1}")
print(f"i was {adjective3}!")
